// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhfN4gtvZotqDQEGRcuTFJAzqt7HtzMtI',
    appId: '1:752491982850:web:a3e6d3afc0f4b1cbe4771b',
    messagingSenderId: '752491982850',
    projectId: 'eventeasee-48de7',
    authDomain: 'eventeasee-48de7.firebaseapp.com',
    storageBucket: 'eventeasee-48de7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC34U_pu3XfZDsl0d1s3DxHLcx7v3GLALc',
    appId: '1:752491982850:android:eca63c39c5d6319ae4771b',
    messagingSenderId: '752491982850',
    projectId: 'eventeasee-48de7',
    storageBucket: 'eventeasee-48de7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5oIvhQJyXNAUwfHDjlIW0O7HIgC1vvKE',
    appId: '1:752491982850:ios:5b34861799e458a2e4771b',
    messagingSenderId: '752491982850',
    projectId: 'eventeasee-48de7',
    storageBucket: 'eventeasee-48de7.firebasestorage.app',
    iosBundleId: 'com.example.eventeasee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5oIvhQJyXNAUwfHDjlIW0O7HIgC1vvKE',
    appId: '1:752491982850:ios:5b34861799e458a2e4771b',
    messagingSenderId: '752491982850',
    projectId: 'eventeasee-48de7',
    storageBucket: 'eventeasee-48de7.firebasestorage.app',
    iosBundleId: 'com.example.eventeasee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhfN4gtvZotqDQEGRcuTFJAzqt7HtzMtI',
    appId: '1:752491982850:web:45f92cb21f61b79fe4771b',
    messagingSenderId: '752491982850',
    projectId: 'eventeasee-48de7',
    authDomain: 'eventeasee-48de7.firebaseapp.com',
    storageBucket: 'eventeasee-48de7.firebasestorage.app',
  );
}
